### ISSUE TITLE
Occasional InternalServerError on address validation

### ISSUE THREAD

**Issue by vdolbilov** [taxjar/taxjar-ruby#48]
Hi,

We use the `validate_address` to verify state information for zipcodes. 99% of the time it works perfectly. Every once in a while, we get a `Taxjar::Error::InternalServerError: Something unexpected went wrong` error response.

The most recent one happened with a zipcode of "94010" which is a valid CA zipcode and returned correctly when ran again.

ruby 2.4.6
taxjar-ruby 2.4.1

Do you have any recommendations besides trying the request multiple times when the error happens?

Thanks!

**Comment by ScottRudiger** [comment]
@vdolbilov Thanks for the issue! The error you're seeing occasionally is likely due to the [API being down](https://status.taxjar.com/) for short blips, or just general network hiccups.

To find out more though, the next time this happens you can reach out to support@taxjar.com and we'll be able to dig in to our logs to know for sure.

I'm going to close the issue for now, but please comment again if you'd like to add anymore detail.
